<% ci_opts = " -r features --color --tags ~@on_demand --tags ~@wip --tags ~@unstable --tags ~@manual --tags ~@pending --format progress -o results/progress.log --format junit -o results/junit/ --format json -o results/cucumber.json --format Cucumber::Blinkbox::Formatter::Html -o results/features_report.html --format pretty "  %>
<% grid_hub_ip =          " GRID_HUB_IP=172.17.51.12 " %>
<% grid_opts_nodejs =     " GRID=true PLATFORM=WINDOWS BROWSER_NAME=firefox " %>
<% grid_opts_qa =         " GRID=true PLATFORM=VISTA BROWSER_NAME=firefox " %>
<% grid_opts_production = " GRID=true PLATFORM=XP BROWSER_NAME=firefox " %>
<% grid_opts_tablet_qa =  "GRID=true PLATFORM=ANDROID BROWSER_NAME=android" %>

default:              -p local_debug
local_debug:          -r features --tags ~@wip GRID=false SERVER=QA DEBUG=true

ci-no-grid:           <%= ci_opts %>
ci-smoke-local:       <%= ci_opts %> --tags @smoke SERVER=LOCALHOST FAIL_FAST=true
ci-smoke-nodejs:      <%= ci_opts %> <%= grid_hub_ip %> <%= grid_opts_nodejs %> --tags @smoke SERVER=NODEJS-INTERNAL FAIL_FAST=true
ci-smoke-qa:          <%= ci_opts %> <%= grid_hub_ip %> <%= grid_opts_qa %> --tags @smoke SERVER=QA
ci-smoke-production:  <%= ci_opts %> <%= grid_hub_ip %> <%= grid_opts_production %> --tags @smoke --tags @production SERVER=PRODUCTION

ci-regression-nodejs: <%= ci_opts %> <%= grid_hub_ip %> <%= grid_opts_nodejs %> --tags ~@smoke SERVER=NODEJS-INTERNAL
ci-regression-qa:     <%= ci_opts %> <%= grid_hub_ip %> <%= grid_opts_qa %> --tags ~@smoke SERVER=QA

local_debug_tablet:  <%= ci_opts %> <%= grid_hub_ip %> <%= grid_opts_tablet_qa %> --tags @smoke SERVER=PRODUCTION

#mac-safari: -r features --tags ~@wip GRID=TRUE PLATFORM=MAC BROWSER_NAME=SAFARI BROWSER_VERSION=6.0.4 --no-multiline -i -s --format progress
#mac-firefox: -r features --tags ~@wip GRID=TRUE PLATFORM=MAC BROWSER_NAME=FIREFOX BROWSER_VERSION=21.0 --no-multiline -i -s --format progress
#mac-chrome: -r feature --tags ~@wip GRID=TRUE PLATFORM=MAC BROWSER_NAME=CHROME BROWSER_VERSION=26.0.1410.65 --no-multiline -i -s --format progress

#win7-ie: -r feature --tags ~@wip GRID=TRUE PLATFORM=WINDOWS BROWSER_NAME=IE BROWSER_VERSION=9.0.8112.16421 --no-multiline -i -s --format progress
#win7-firefox: -r feature --tags ~@wip GRID=TRUE PLATFORM=WINDOWS BROWSER_NAME=FIREFOX BROWSER_VERSION=21.0 --no-multiline -i -s --format progress
#win7-chrome: -r feature --tags ~@wip GRID=TRUE PLATFORM=WINDOWS BROWSER_NAME=CHROME BROWSER_VERSION=26.0.1410.64 --no-multiline -i -s --format progress

#win-vista-ie: -r feature --tags ~@wip GRID=TRUE PLATFORM=VISTA BROWSER_NAME=IE BROWSER_VERSION=9.0.8112.16421 --no-multiline -i -s --format progress
#win-vista-firefox: -r feature --tags ~@wip GRID=TRUE PLATFORM=VISTA BROWSER_NAME=FIREFOX BROWSER_VERSION=21.0 --no-multiline -i -s --format progress
#win-vista-chrome: -r feature --tags ~@wip GRID=TRUE PLATFORM=VISTA BROWSER_NAME=CHROME BROWSER_VERSION=6.0.1410.64 --no-multiline -i -s --format progress

#win8-ie: -r feature --tags ~@wip GRID=TRUE PLATFORM=WIN8 BROWSER_NAME=IE BROWSER_VERSION=9.0.8112.16421 --no-multiline -i -s --format progress
#win8-firefox: -r feature --tags ~@wip GRID=TRUE PLATFORM=WIN8 BROWSER_NAME=FIREFOX BROWSER_VERSION=21.0 --no-multiline -i -s --format progress
#win8-chrome: -r feature --tags ~@wip GRID=TRUE PLATFORM=WIN8 BROWSER_NAME=CHROME BROWSER_VERSION=26.0.1410.64 --no-multiline -i -s --format progress

#win-vista-ie: -r feature --tags ~@wip GRID=TRUE PLATFORM=XP BROWSER_NAME=IE BROWSER_VERSION=8.0.6001.18702 --no-multiline -i -s --format progress
#win-vista-firefox: -r feature --tags ~@wip GRID=TRUE PLATFORM=XP BROWSER_NAME=FIREFOX BROWSER_VERSION=21.0 --no-multiline -i -s --format progress
#win-vista-chrome: -r feature --tags ~@wip GRID=TRUE PLATFORM=XP BROWSER_NAME=CHROME BROWSER_VERSION=26.0.1410.64 --no-multiline -i -s --format progress

# COMMAND LINE OPTIONS 
# SERVER: LOCALHOST, NODEJS-INTERNAL, QA, STAGING, PRODUCTION
# DEVICE: MOBILE, TABLET-PORTRAIT, TABLET-LANDSCAPE, DESKTOP

