<% ci_formatting =    " --format pretty --format junit -o results/junit/ --format Cucumber::Blinkbox::Formatter::Html -o results/features_report.html " %>
<% ci_tags =          " --tags ~@unstable --tags ~@on_demand --tags ~@wip --tags ~@manual --tags ~@pending --tags ~@to_remove " %>
<% ci_tags_unstable = " --tags  @unstable --tags ~@on_demand --tags ~@wip --tags ~@manual --tags ~@pending --tags ~@to_remove" %>
<% ci_opts =          ci_tags          + ci_formatting + " -r features WAIT_FOR_AJAX=true " %>
<% ci_opts_unstable = ci_tags_unstable + ci_formatting + " -r features WAIT_FOR_AJAX=true " %>

<% grid_hub_ip =          " GRID_HUB_IP=172.17.51.12 " %>
<% grid_opts_test =       grid_hub_ip + " GRID=true PLATFORM=WINDOWS BROWSER_NAME=chrome " %>
<% grid_opts_dev =        grid_hub_ip + " GRID=true PLATFORM=WINDOWS BROWSER_NAME=chrome " %>
<% grid_opts_qa =         grid_hub_ip + " GRID=true PLATFORM=VISTA BROWSER_NAME=chrome " %>
<% grid_opts_production = grid_hub_ip + " GRID=true PLATFORM=XP BROWSER_NAME=chrome " %>
<% grid_opts_tablet_qa =  grid_hub_ip + " GRID=true PLATFORM=ANDROID BROWSER_NAME=android " %>

default:              -p local_debug
local_debug:          -r features --tags ~@wip GRID=false SERVER=TEST DEBUG=true

ci-no-grid:                        <%= ci_opts %>

ci-local-smoke:                    <%= ci_opts %> SERVER=LOCALHOST --tags @smoke FAIL_FAST=false
ci-vagrant-smoke:                  <%= ci_opts %> SERVER=LOCALHOST --tags @smoke --tags @production BROWSER_NAME=firefox HEADLESS=true FAIL_FAST=true

ci-test-smoke:                     <%= ci_opts %>          SERVER=TEST --tags  @smoke FAIL_FAST=false
ci-test-sanity:                    <%= ci_opts %>          SERVER=TEST --tags  @sanity FAIL_FAST=false
ci-test-regression:                <%= ci_opts %>          SERVER=TEST --tags ~@smoke --tags ~@sanity
ci-test-smoke-unstable:            <%= ci_opts_unstable %> SERVER=TEST --tags  @smoke
ci-test-sanity-unstable:           <%= ci_opts_unstable %> SERVER=TEST --tags  @sanity
ci-test-regression-unstable:       <%= ci_opts_unstable %> SERVER=TEST --tags ~@smoke --tags ~@sanity

ci-dev-smoke:                      <%= ci_opts %>          SERVER=DEV --tags  @smoke                 --tags @production
ci-dev-sanity:                     <%= ci_opts %>          SERVER=DEV --tags  @sanity                --tags @production
ci-dev-regression:                 <%= ci_opts %>          SERVER=DEV --tags ~@smoke --tags ~@sanity --tags @production
ci-dev-regression-unstable:        <%= ci_opts_unstable %> SERVER=DEV --tags ~@smoke --tags ~@sanity --tags @production

ci-production-smoke:               <%= ci_opts %>          SERVER=PRODUCTION --tags  @smoke                 --tags @production
ci-production-sanity:              <%= ci_opts %>          SERVER=PRODUCTION --tags  @sanity                --tags @production
ci-production-regression:          <%= ci_opts %>          SERVER=PRODUCTION --tags ~@smoke --tags ~@sanity --tags @production
ci-production-regression-unstable: <%= ci_opts_unstable %> SERVER=PRODUCTION --tags ~@smoke --tags ~@sanity --tags @production


#mac-safari: -r features --tags ~@wip GRID=TRUE PLATFORM=MAC BROWSER_NAME=SAFARI BROWSER_VERSION=6.0.4 --no-multiline -i -s --format progress
#mac-firefox: -r features --tags ~@wip GRID=TRUE PLATFORM=MAC BROWSER_NAME=FIREFOX BROWSER_VERSION=21.0 --no-multiline -i -s --format progress
#mac-chrome: -r feature --tags ~@wip GRID=TRUE PLATFORM=MAC BROWSER_NAME=CHROME BROWSER_VERSION=26.0.1410.65 --no-multiline -i -s --format progress

#win7-ie: -r feature --tags ~@wip GRID=TRUE PLATFORM=WINDOWS BROWSER_NAME=IE BROWSER_VERSION=9.0.8112.16421 --no-multiline -i -s --format progress
#win7-firefox: -r feature --tags ~@wip GRID=TRUE PLATFORM=WINDOWS BROWSER_NAME=FIREFOX BROWSER_VERSION=21.0 --no-multiline -i -s --format progress
#win7-chrome: -r feature --tags ~@wip GRID=TRUE PLATFORM=WINDOWS BROWSER_NAME=CHROME BROWSER_VERSION=26.0.1410.64 --no-multiline -i -s --format progress

#win-vista-ie: -r feature --tags ~@wip GRID=TRUE PLATFORM=VISTA BROWSER_NAME=IE BROWSER_VERSION=9.0.8112.16421 --no-multiline -i -s --format progress
#win-vista-firefox: -r feature --tags ~@wip GRID=TRUE PLATFORM=VISTA BROWSER_NAME=FIREFOX BROWSER_VERSION=21.0 --no-multiline -i -s --format progress
#win-vista-chrome: -r feature --tags ~@wip GRID=TRUE PLATFORM=VISTA BROWSER_NAME=CHROME BROWSER_VERSION=6.0.1410.64 --no-multiline -i -s --format progress

#win8-ie: -r feature --tags ~@wip GRID=TRUE PLATFORM=WIN8 BROWSER_NAME=IE BROWSER_VERSION=9.0.8112.16421 --no-multiline -i -s --format progress
#win8-firefox: -r feature --tags ~@wip GRID=TRUE PLATFORM=WIN8 BROWSER_NAME=FIREFOX BROWSER_VERSION=21.0 --no-multiline -i -s --format progress
#win8-chrome: -r feature --tags ~@wip GRID=TRUE PLATFORM=WIN8 BROWSER_NAME=CHROME BROWSER_VERSION=26.0.1410.64 --no-multiline -i -s --format progress

#win-vista-ie: -r feature --tags ~@wip GRID=TRUE PLATFORM=XP BROWSER_NAME=IE BROWSER_VERSION=8.0.6001.18702 --no-multiline -i -s --format progress
#win-vista-firefox: -r feature --tags ~@wip GRID=TRUE PLATFORM=XP BROWSER_NAME=FIREFOX BROWSER_VERSION=21.0 --no-multiline -i -s --format progress
#win-vista-chrome: -r feature --tags ~@wip GRID=TRUE PLATFORM=XP BROWSER_NAME=CHROME BROWSER_VERSION=26.0.1410.64 --no-multiline -i -s --format progress

# COMMAND LINE OPTIONS
# SERVER: LOCALHOST, TEST, DEV, PRODUCTION
# DEVICE: MOBILE, TABLET-PORTRAIT, TABLET-LANDSCAPE, DESKTOP
